
[WINDOWS]

; SEMICLIP_SOLID_BYTE     (non-ReHLDS) [index]
OFFSDEC: 2

; SEMICLIP_SOLID_BYTE_RE  (ReHLDS)     [index]
OFFSDEC: 6

; IDENTIFIER              (non-ReHLDS) [may also be a valid Windows symbol]
Trigger in clipping list

; IDENTIFIER              (ReHLDS)     [may also be a valid Windows symbol]
%s: Trigger in clipping list

; SIGNATURE               (non-ReHLDS)
SIG: AB CD EF FE DC BA FF FF FF FF FF FF 66 66 66 66 66 66 AA AA AA AA AA AA

; SIGNATURE               (ReHLDS)
SIG: AB CD EF FE DC BA FF FF FF FF FF FF 66 66 66 66 66 66 AA AA AA AA AA AA

; BYTES SEARCH RANGE
OFFSDEC: 4096

; BACK POSITION TO START COMPARING BYTES FROM [must be 0 if using a valid signature for '::SV_ClipToLinks()' on Windows]
OFFSDEC: 512

[LINUX]

; SEMICLIP_SOLID_BYTE     (non-ReHLDS) [index]
OFFSDEC: 2

; SEMICLIP_SOLID_BYTE_RE  (ReHLDS)     [index]
OFFSDEC: 6

; SYMBOL                  (non-ReHLDS)
SV_ClipToLinks

; SYMBOL                  (ReHLDS)
_Z14SV_ClipToLinksP10areanode_sP10moveclip_s

; SIGNATURE               (non-ReHLDS)
SIG: 55 57 56 53 81 ? ? ? ? ? 8B ? ? ? ? ? ? 8B ? ? ? ? ? ? 8B ? ? 8D

; SIGNATURE               (ReHLDS)
SIG: AB CD EF FE DC BA FF FF FF FF FF FF 66 66 66 66 66 66 AA AA AA AA AA AA

; BYTES SEARCH RANGE
OFFSDEC: 4096

; BACK POSITION TO START COMPARING BYTES FROM
OFFSDEC: 0
