
[WINDOWS]

; SEMICLIP_PATCH_BYTES      (non-ReHLDS)
OFFSDEC: 3

; SEMICLIP_PATCH_BYTES_RE   (ReHLDS)
OFFSDEC: 7

; SEMICLIP_SOLID_BYTE       (non-ReHLDS)
OFFSDEC: 2

; SEMICLIP_SOLID_BYTE_RE    (ReHLDS)
OFFSDEC: 6

; IDENTIFIER (non-ReHLDS);  right now, it's a const. string; can also be a symbol, however, Windows symbols are rare
Trigger in clipping list

; IDENTIFIER (ReHLDS);      right now, it's a const. string; can also be a symbol, however, Windows symbols are rare
%s: Trigger in clipping list

; SIGNATURE (any Engine, just in case, unused for now)
SIG: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF EF EF EF EF EF EF EF EF EF EF 66 66 66 66 66 66 66

; BYTES SEARCH RANGE
OFFSDEC: 4096

; BACK POSITION TO START COMPARING BYTES FROM (must be 0 if using a valid signature for SV_ClipToLinks on Windows)
OFFSDEC: 512

[LINUX]

; SEMICLIP_PATCH_BYTES      (non-ReHLDS)
OFFSDEC: 3

; SEMICLIP_PATCH_BYTES_RE   (ReHLDS)
OFFSDEC: 7

; SEMICLIP_SOLID_BYTE       (non-ReHLDS)
OFFSDEC: 2

; SEMICLIP_SOLID_BYTE_RE    (ReHLDS)
OFFSDEC: 6

; SYMBOL (non-ReHLDS)
SV_ClipToLinks

; SYMBOL (ReHLDS)
_Z14SV_ClipToLinksP10areanode_sP10moveclip_s

; SIGNATURE (any Engine, just in case)
SIG: 55 57 56 53 81 ? ? ? ? ? 8B ? ? ? ? ? ? 8B ? ? ? ? ? ? 8B ? ? 8D

; BYTES SEARCH RANGE
OFFSDEC: 4096

; BACK POSITION TO START COMPARING BYTES FROM
OFFSDEC: 0
