
[WINDOWS]

; OPCODE     (non-ReHLDS) [cmp]
OFFSHEX: 83

; OPCODE     (ReHLDS)     [cmp]
OFFSHEX: 83

; BYTE VAL   (non-ReHLDS) [#define SOLID_SLIDEBOX ... (what to search for)]
OFFSDEC: 3

; BYTE VAL   (ReHLDS)     [#define SOLID_SLIDEBOX ... (what to search for)]
OFFSDEC: 3

; SOLID BYTE (non-ReHLDS) [index, after opcode]
OFFSDEC: 2

; SOLID BYTE (ReHLDS)     [index, after opcode]
OFFSDEC: 6

; PATCH BYTE (non-ReHLDS) [to be patched to]
OFFSDEC: 0

; PATCH BYTE (ReHLDS)     [to be patched to]
OFFSDEC: 0

; IDENTIFIER (non-ReHLDS) [may also be a valid Windows symbol]
Trigger in clipping list

; IDENTIFIER (ReHLDS)     [may also be a valid Windows symbol]
%s: Trigger in clipping list

; SIGNATURE  (non-ReHLDS) [used as fallback method]
SIG: 55 8B ? 83 ? ? 53 8B ? ? 56 8B ? ? 57 90 8B ? ? 8D ? ? 89 ? ? 3B ? 0F ? ? ? ? ? 8B ? ? 83 ? ? 8B ? ? ? ? ? 85 ? 74 ? 8B ? ? 85 ? 74

; SIGNATURE  (ReHLDS)     [used as fallback method]
SIG: 55 8B ? 81 ? ? ? ? ? 53 56 8B ? 89 ? ? 57 89 ? ? 8B ? 8B ? ? 8D ? ? D9 ? 89 ? ? 3B ? 74

; RANGE      (non-ReHLDS) [byte search range]
OFFSDEC: 4096

; RANGE      (ReHLDS)     [byte search range]
OFFSDEC: 4096

; BACK POS   (non-ReHLDS) [back pos. to start comparing bytes from, must be 0 if using a valid sig. for '::SV_ClipToLinks()' on Windows]
OFFSDEC: 512

; BACK POS   (ReHLDS)     [back pos. to start comparing bytes from, must be 0 if using a valid sig. for '::SV_ClipToLinks()' on Windows]
OFFSDEC: 512

[LINUX]

; OPCODE     (non-ReHLDS) [cmp]
OFFSHEX: 83

; OPCODE     (ReHLDS)     [cmp]
OFFSHEX: 83

; BYTE VAL   (non-ReHLDS) [#define SOLID_SLIDEBOX ... (what to search for)]
OFFSDEC: 3

; BYTE VAL   (ReHLDS)     [#define SOLID_SLIDEBOX ... (what to search for)]
OFFSDEC: 3

; SOLID BYTE (non-ReHLDS) [index, after opcode]
OFFSDEC: 2

; SOLID BYTE (ReHLDS)     [index, after opcode]
OFFSDEC: 6

; PATCH BYTE (non-ReHLDS) [to be patched to]
OFFSDEC: 0

; PATCH BYTE (ReHLDS)     [to be patched to]
OFFSDEC: 0

; SYMBOL     (non-ReHLDS)
SV_ClipToLinks

; SYMBOL     (ReHLDS)
_Z14SV_ClipToLinksP10areanode_sP10moveclip_s

; SIGNATURE  (non-ReHLDS) [used as fallback method]
SIG: 55 57 56 53 81 ? ? ? ? ? 8B ? ? ? ? ? ? 8B ? ? ? ? ? ? 8B ? ? 8D

; SIGNATURE  (ReHLDS)     [used as fallback method]
SIG: E8 ? ? ? ? 05 ? ? ? ? 55 57 56 53 83 ? ? 8D ? ? ? ? ? 89 ? ? ? 8D ? ? ? ? ? 89 ? ? ? 8B

; RANGE      (non-ReHLDS) [byte search range]
OFFSDEC: 4096

; RANGE      (ReHLDS)     [byte search range]
OFFSDEC: 4096

; BACK POS   (non-ReHLDS) [back pos. to start comparing bytes from, must be 0 if using a valid sig. for '::SV_ClipToLinks()' on Windows]
OFFSDEC: 0

; BACK POS   (ReHLDS)     [back pos. to start comparing bytes from, must be 0 if using a valid sig. for '::SV_ClipToLinks()' on Windows]
OFFSDEC: 0
